### PR TITLE
Implements Soft Randomization and Messy Collaboration

### PR DESCRIPTION
**Pull request by NeelayS**
These techniques target improving model robustness and generalization. If/when the directory structure of the library is modified, maybe we can group implementations according to the purpose they serve.  
Issue #47

### CODE REVIEW

**Comment by Het-Shah** [comment]
> If/when the directory structure of the library is modified, maybe we can group implementations according to the purpose they serve.

Yup sounds like a good plan to me.

**Comment by Het-Shah** [comment]
Let me know if you are done. I'll review it then finally.

**Comment by NeelayS** [comment]
Done now.

**Comment by Het-Shah** [comment]
Will merge after this build is done.

**Pull request merged**
