### PR TITLE
Quantization

### PR DESCRIPTION
**Pull request by avishreekh**
Solves #72

### CODE REVIEW

**Comment by Het-Shah** [comment]
What is this? why are there 30 commits? Pull the repo properly  otherwise we will lose the changes made in between.

**Comment by avishreekh** [comment]
I created a new branch from the last one (bert2lstm)

**Comment by avishreekh** [comment]
That is why it shows so many commits

**Comment by Het-Shah** [comment]
You should create a branch from master. I am closing this PR. Please make a proper branch.

**Pull request closed without merging**
