### PR TITLE
Born Again Neural Networks

### PR DESCRIPTION
**Pull request by khizirsiddiqui**
Issue #42 
 - Add BANN Module
 - Add tests for BANN

I have also moved the main implementation in `BaseClass::train_student()` to a new function `BaseClass::_train_student()` and `BaseClass::evaluate` to ``BaseClass::_evaluate_model()`. `BANN` trains several generation of models to create an ensemble. This structure allows more flexibility around the `evaluate` and `train_student` methods.

Remaining
 - Documentation

### CODE REVIEW

**Comment by khizirsiddiqui** [comment]
I will fix error in next commit with the documentation.

**Comment by NeelayS** [comment]
@khizirsiddiqui Since we converted loss_fn in the BaseClass to a torch module, the other paper implementations will have to be modified as well, won't they ? Will you be working on that in this PR ?

**Comment by khizirsiddiqui** [comment]
@NeelayS It should be better if you could open a separate PR for that.

**Comment by khizirsiddiqui** [comment]
@Het-Shah The tests fail to load the models from file, BANN creates and saves a model for each generation. Since saving and loading won't be possible in TravisCI, could you please test it yourself?
And I will be removing `evaluate()` call from tests also.

**Comment by Het-Shah** [comment]
Ok, Remove it no worries. There are memory issues.

**Comment by Het-Shah** [comment]
I'll merge once tests are done.

**Comment by NeelayS** [comment]
> @Het-Shah The tests fail to load the models from file, BANN creates and saves a model for each generation. Since saving and loading won't be possible in TravisCI, could you please test it yourself?
> And I will be removing `evaluate()` call from tests also.

Do add your paper to README as well :)

**Comment by khizirsiddiqui** [comment]
Thanks @NeelayS . :_tuzki_pheew:

**Comment by NeelayS** [comment]
:_tuzki_pheew:  ??

**Comment by Het-Shah** [comment]
Merging.

**Pull request merged**
