### PR TITLE
Add validation on the fly

### PR DESCRIPTION
**Pull request by avishreekh**
Added validation on the fly (#95):

1. Ensured that an evaluate method is present in KD algorithms which is called while training
2. Best model is saved based on validation performance

Some questions (and potential problems)

1. Did not add the enhancement to DML and TAKD as that would require substantial changes to their evaluate methods. Please let me know if these can be changed.
2. Evaluation methods seem to be returning the accuracy in most cases (should we also not be returning the model outputs if the evaluate method is used independently?). The `_evaluate_model` method returns outputs also but this is ignored in the `evaluate` method, is there a reason for doing so?

Please let me know if the current changes need any additional modifications.

Thanks!

### CODE REVIEW

**Comment by avishreekh** [comment]
Hi @NeelayS @Het-Shah,

In Deep Mutual Learning, how do we perform validation? (Currently we find the best training performance in the entire cohort)
1. Do we validate each student model and consider the best accuracy per student?
2. Do we validate the best student model and consider the best accuracy for the entire cohort?

Thanks!

**Comment by NeelayS** [comment]
In the paper, they use a cohort of 2 students and report results of both. So I guess it would best to validate every student model.

**Comment by avishreekh** [comment]
Thank you! If so, should we be saving the weights that give the best accuracy irrespective of which student they come from? (Validate each student and if any student gives better performance than before (could be from any student), store its weights as the best set of weights)

**Comment by avishreekh** [comment]
Let me know if this looks good for DML @NeelayS @Het-Shah 

Thank you!

**Review by Het-Shah — APPROVED** [review]

**Comment by Het-Shah** [comment]
Looks good to me!

**Pull request merged**
