### PR TITLE
Add BaseClass

### PR DESCRIPTION
**Pull request by Het-Shah**
Now that we have a good amount of implementations. We can start giving a shape to this library. Let me know of your thoughts on this direction @NeelayS @khizirsiddiqui @avishreekh

### CODE REVIEW

**Comment by Het-Shah** [comment]
So with this, it should be easier to implement anything new. Also, let me know if anything else can be added to the base class or not.

**Comment by khizirsiddiqui** [comment]
Multiple Loss functions can be used with KD loss, like Relational KD and Noisy Teacher together. It will be difficult to combine the permutations (they are many already). Or for now we can just focus on individual implementations?

**Comment by Het-Shah** [comment]
> Multiple Loss functions can be used with KD loss, like Relational KD and Noisy Teacher together. It will be difficult to combine the permutations (they are many already).

I don't think this is a concern, we can easily implement these using this structure.

**Comment by Het-Shah** [comment]
In my opinion it gives a lot of structure to our code.

**Comment by NeelayS** [comment]
But will this provide the user the flexibility to combine multiple KD loss functions ?

**Comment by Het-Shah** [comment]
Yea why not, I'll push the original one in some time let me know if that makes sense.

**Comment by Het-Shah** [comment]
See this, and let me know. I haven't tested this rigorously but the code runs more or less.

**Comment by NeelayS** [comment]
From what I understand, we are targetting usage to be something like -

`from KD_Lib.<> import Noisy_Teacher

distiller = Noisy_Teacher(teacher, student,.....)
distiller.train_teacher()
distiller.train_student()
distiller.evaluate() `

Am I right ?

**Comment by Het-Shah** [comment]
yes

**Comment by NeelayS** [comment]
> yes

Now, suppose I want to combine the methods of Noisy_Teacher and say TAKD, which would mean somehow combining their loss functions, how would I do that ?

**Comment by Het-Shah** [comment]
You will need to write a custom loss and reimplement the teacher/student training functions with the changes

**Comment by Het-Shah** [comment]
But this provides structure to any implementations that we have in my opinion. Because currently there are a lot of differences in the current implementations.

**Comment by Het-Shah** [comment]
> Now, suppose the user wants to combine the methods of Noisy_Teacher and say TAKD

Currently we don't support this right?

**Comment by NeelayS** [comment]
> > Now, suppose the user wants to combine the methods of Noisy_Teacher and say TAKD
> 
> Currently we don't support this right?

Oh, okay.

**Comment by Het-Shah** [comment]
If we want TAKD to be using methods of Noisy_Teacher. we can have multiple inheritance for TAKD.

**Comment by Het-Shah** [comment]
The current `original_paper.py` file is just an example. We can probably work more on all implementations if this idea seems good to you all.

**Comment by Het-Shah** [comment]
Also I  would suggest any new type of model architecture to be in the `KD_Lib/models` directory to maintain the hierarchy.

**Comment by Het-Shah** [comment]
I am merging this. If you have any issues with this approach, feel free to open up an issue.

**Pull request merged**
