### PR TITLE
Error handling and minor bug fixes in CSKD

### PR DESCRIPTION
**Pull request by ashwinvaswani**

### CODE REVIEW

**Comment by NeelayS** [comment]
Currently, for the algos which don't use teacher networks (eg. Self Training), we haven't inherited from the base class to avoid having redundant methods and parameters. Do you think that should be done here as well ?

**Comment by ashwinvaswani** [comment]
@Het-Shah As @NeelayS suggested, do you think we should keep it uniform as in the above PR OR not inherit from base class for self-training implementations?

**Comment by Het-Shah** [comment]
I think this is fine. We should be inheriting BaseClass as much as possible to maintain that abstraction.

**Comment by ashwinvaswani** [comment]
Okay

**Comment by khizirsiddiqui** [comment]
Also, can't we simply remove the `teacher_model` and `optimizer_teacher` arguments to CSKD and pass `None` when initializing for BaseClass?

**Pull request merged**
