### PR TITLE
Implements TAKD

### PR DESCRIPTION
**Pull request by khizirsiddiqui**
- Resolves issue #6 
- few minor edits in ```CONTRIBUTING.rst```

### CODE REVIEW

**Comment by khizirsiddiqui** [comment]
I have made a minor change to the referred paper in my experiment.
Teacher teaches TA1, Teacher and TA1 both teach TA2 and finally TA1 and TA2 distill knowledge to the student net.

**Comment by Het-Shah** [comment]
Resolve the build error, else everything seems to be good to me.

**Comment by Het-Shah** [comment]
Lite le

**Comment by Het-Shah** [comment]
Tests are going out. :)

**Pull request merged**
