### PR TITLE
Optuna and fixes

### PR DESCRIPTION
**Pull request by NeelayS**
- Added Optuna tutorial
- Added tutorial file names to `index.rst`
- Remove imports from `KD_Lib/__init__.py`

### CODE REVIEW

**Review by Het-Shah — APPROVED** [review]
Nice looks good to me.

**Comment by Het-Shah** [comment]
Let me know if this is ready to merge or not.

**Comment by NeelayS** [comment]
Yup, good to merge

**Comment by NeelayS** [comment]
Good to merge now

**Comment by NeelayS** [comment]
Good to merge now

**Comment by Het-Shah** [comment]
Resolve these conflicts once

**Comment by NeelayS** [comment]
Some problem with Black again ? Formatting has been done locally.

**Comment by Het-Shah** [comment]
I don't think we should have anymore Black issues now

**Comment by Het-Shah** [comment]
Update the black version, i ran it locally for your branch it works. Run `pip install -U black`

**Pull request merged**
