### PR TITLE
Attention Transfer

### PR DESCRIPTION
**Pull request by khizirsiddiqui**
Issue #15 
 - add activation based attention transfer loss.

### CODE REVIEW

**Comment by Het-Shah** [comment]
How does it sound to move the train and evaluate to a common folder. I see it being almost similar in every implementation that we have. So for a new implementation we would just have to write the loss and some other utils files?

**Comment by khizirsiddiqui** [comment]
Sounds good, will send a PR soon. :+1:

**Comment by Het-Shah** [comment]
Yea cool, am merging this as of now.

**Comment by NeelayS** [comment]
But some papers might need modifications to the train function as well. Like mine which was merged today.

**Comment by NeelayS** [comment]
> Sounds good, will send a PR soon. 👍

My PR which was merged today had a slightly different train function. Do look at that when you are shifting.

**Pull request merged**
